### ISSUE TITLE
Passing a third argument to "Symfony\Component\HttpFoundation\HeaderBag::get()" is deprecated since Symfony 4.4

### ISSUE THREAD

**Issue by stlrnz** [Toflar/psr6-symfony-http-cache-store#21]
When using the Psr6Store in Symfony 4.4 I get the follwing warning:

> Passing a third argument to "Symfony\Component\HttpFoundation\HeaderBag::get()" is deprecated since Symfony 4.4, use method "all()" instead

I think this is caused by https://github.com/Toflar/psr6-symfony-http-cache-store/blob/7538b8b7dccb61718379e3c8d12a83137a693c39/src/Psr6Store.php#L260

In Symfony 5, the third Parameter is removed: https://github.com/symfony/http-foundation/blob/5dc0db5026f2b611cb8910a1f465e95eafd84c2e/HeaderBag.php#L108

Since this package is marked as compatible with Symfony 5, this should be handled as a bug.

**Comment by Toflar** [comment]
Hey Stefan, thanks for reporting. That one wasn't caught because it's actually working. The parameter is just ignored for Symfony 4 and we don't get the 4.4 deprecation notice because the CI tests Symfony 5.x and lowest would be 3.4 🙈 
Can you check if https://github.com/Toflar/psr6-symfony-http-cache-store/pull/22 removes the deprecation notice for you? 😊

**Comment by stlrnz** [comment]
I can confirm that this fixes the deprecation notice in Symfony 4.4.

Thank your for your quick support! 👍

**Comment by Toflar** [comment]
Just released 2.1.2, cheers 🍺
